#!/usr/bin/env python
# -*- coding: utf-8 -*-

PYOWM_VERSION = (3, 0, 0)
AGRO_API_VERSION = (1, 0, 0)
AIRPOLLUTION_API_VERSION = (3, 0, 0)
ALERT_API_VERSION = (3, 0, 0)
STATIONS_API_VERSION = (3, 0, 0)
UVINDEX_API_VERSION = (3, 0, 0)
WEATHER_API_VERSION = (2, 5, 0)
